server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/websky
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 1913896486@qq.com
    password: 邮箱授权码
mybatis-plus:
  type-aliases-package: com.cen.websky.entity
#  global-config:
#    db-config:
#      id-type: auto # 全局id类型为自增长
  mapper-locations: "classpath*:/mapper/**/*.xml" # Mapper.xml文件地址，当前这个是默认值。
aliyun:
  oss:
    accessKeyId: 身份ID
    accessKeySecret: 身份密钥
    bucketName: websky-cloud
    endpoint: https://oss-cn-shenzhen.aliyuncs.com